travis:
  secure:
    BINSTAR_TOKEN: KBNgyAkDtqdyNS7e7t71kutKhkHGgj/aTQjHlHzomTVCUqINvxKAHnpr1g6guCm8J9zsTvf1RHc6A0kutzG9GiK3S5OzA89HevBc/WXy60AfKdkSvpfDmrvmQeB3HA8YqJcTIwa2YnWwx/T/c17NUNzkOOiuyjLTknxPpLeeB7a9SYZ1MAzcLStcYt0ZLeizQS+MIf355pyNiZMY7mlw/ISInN6976IqLbQeYsOcugMk6k76rPQACj1nbH1lPBi7AEkDenExIiK6jHVRjuJwghS99zgKt4PlIMwXZJEQBtY7Ca8zlWWeTQw79kouY5QgHqB5tpyA2gSrDT2ngraRijYGnsYGb1hTjQbl1EaTPPexQYwN95hHUzX36xqeOM7db1dFoNTDDmPU+yJywnyOS73lcLIqwV5YIAsBdmZrfnm6DWKLd7k2zEpJGhZ1r6nyIE8zpfSjO5/WCxr+zyNvSf4b2LFramZ0aE135rMGtskKeKOMb5zARnfpUq3KMXzraVfssB2n9QzJ2httg5nqLZxqOk95pKQLZOkpq5wx7EUpTSvCxpTMp6MGuVepq7IkEPG/RwkJagpcz0tNg0qJt1mbonBUsUmG+Jy1wF2IY6GkC8H43XLleV/pK2eSh6muqaH+jp33sCPSECUNBu9uxPgtIhnkY/R8E9NU8mJ2ZQE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
